### ISSUE TITLE
'setterm' não é reconhecido como um comando interno ou externo.

### ISSUE THREAD

**Issue by HenryEvan** [WalderlanSena/toolsrouterbrute#1]
'setterm' não é reconhecido como um comando interno ou externo, um programa operável ou um arquivo em lotes. Traceback (most recent call last):   File "D:\Mídia\Code\3.1 Router\Toolsrouterbrute\trb.py", line 64, in <module>     main();   File "D:\Mídia\Code\3.1 Router\Toolsrouterbrute\trb.py", line 39, in main     authEncode = auth+base64.b64encode(login+':'+password)   File "C:\Users\ander\AppData\Local\Programs\Python\Python310\lib\base64.py", line 58, in b64encode     encoded = binascii.b2a_base64(s, newline=False) TypeError: a bytes-like object is required, not 'str'

**Comment by WalderlanSena** [comment]
@HenryEvan  No Linux, o comando setterm -cursor off é usado para desligar a exibição do cursor do terminal. O cursor é aquela piscante linha vertical (ou bloco) que geralmente indica a posição onde o próximo caractere será inserido quando você digita algo no terminal.

Ao executar setterm -cursor off, você está desativando a exibição do cursor, o que significa que ele não será mais visível no terminal. Isso pode ser útil em várias situações, como quando você deseja ocultar o cursor para fins de apresentação, ao exibir informações na tela em modo de exibição ou até mesmo em alguns jogos de console.

Se você quiser reativar o cursor posteriormente, pode usar setterm -cursor on.

Vale lembrar que o setterm é uma ferramenta específica do Linux e não está disponível nativamente no Windows. Se você deseja fazer algo semelhante no Windows, precisará usar as alternativas que mencionei na resposta anterior, como o Windows Terminal, Cmder ou o WSL.

**Comment by HenryEvan** [comment]
Certo, obrigado! Irei testar no Linux.
